// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evacuation.Infrastructure.Data;

#nullable disable

namespace evacuation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128031441_SeedMasterData")]
    partial class SeedMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssignedPeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ETA")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ZoneId");

                    b.ToTable("EvacuationPlans", (string)null);
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EvacuationStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4464588d-bd4f-4ad9-ba60-217b8b163e61"),
                            CreateDate = new DateTime(2026, 1, 22, 11, 52, 14, 0, DateTimeKind.Unspecified),
                            Description = "พร้อมดำเนินการ",
                            Sequence = 1,
                            StatusCode = "READY"
                        },
                        new
                        {
                            Id = new Guid("423c1ccb-fcff-44f6-a9c5-4e5bcb84f5f6"),
                            CreateDate = new DateTime(2026, 1, 22, 11, 52, 14, 0, DateTimeKind.Unspecified),
                            Description = "กำลังดำเนินการ",
                            Sequence = 2,
                            StatusCode = "INPROGRESS"
                        },
                        new
                        {
                            Id = new Guid("56c51499-c1d3-411a-b7e4-37d43a6e0bda"),
                            CreateDate = new DateTime(2026, 1, 22, 11, 52, 14, 0, DateTimeKind.Unspecified),
                            Description = "เสร็จสิ้น",
                            Sequence = 3,
                            StatusCode = "COMPLETED"
                        });
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripSequence")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("EvacuationTrips", (string)null);
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("UrgencyLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ZoneCode")
                        .IsUnique();

                    b.ToTable("EvacuationZones", (string)null);
                });

            modelBuilder.Entity("evacuation.Domain.Entities.RunningCodes", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("RunningCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "zone",
                            CurrentValue = 0,
                            Prefix = "Z"
                        },
                        new
                        {
                            Name = "vehicle",
                            CurrentValue = 0,
                            Prefix = "V"
                        },
                        new
                        {
                            Name = "plan",
                            CurrentValue = 0,
                            Prefix = "P"
                        });
                });

            modelBuilder.Entity("evacuation.Domain.Entities.VehicleTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e637482-a0c2-45a2-b97e-0c8c87e1b120"),
                            CreateDate = new DateTime(2026, 1, 22, 15, 1, 53, 0, DateTimeKind.Unspecified),
                            TypeName = "bus"
                        },
                        new
                        {
                            Id = new Guid("ddf12d9d-c3e0-460b-9730-145e2016c27d"),
                            CreateDate = new DateTime(2026, 1, 22, 15, 1, 57, 0, DateTimeKind.Unspecified),
                            TypeName = "van"
                        },
                        new
                        {
                            Id = new Guid("bbbd36d6-3b89-4fde-927c-0cddf4d1f9f1"),
                            CreateDate = new DateTime(2026, 1, 22, 15, 2, 1, 0, DateTimeKind.Unspecified),
                            TypeName = "boat"
                        });
                });

            modelBuilder.Entity("evacuation.Domain.Entities.Vehicles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Speed")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationPlan", b =>
                {
                    b.HasOne("evacuation.Domain.Entities.EvacuationStatus", "Status")
                        .WithMany("evacuationPlans")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("evacuation.Domain.Entities.Vehicles", "Vehicle")
                        .WithMany("evacuationPlans")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("evacuation.Domain.Entities.EvacuationZone", "Zone")
                        .WithMany("evacuationPlans")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Vehicle");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationTrip", b =>
                {
                    b.HasOne("evacuation.Domain.Entities.EvacuationPlan", "evacuationPlan")
                        .WithMany("evacuationTrips")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("evacuationPlan");
                });

            modelBuilder.Entity("evacuation.Domain.Entities.Vehicles", b =>
                {
                    b.HasOne("evacuation.Domain.Entities.VehicleTypes", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationPlan", b =>
                {
                    b.Navigation("evacuationTrips");
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationStatus", b =>
                {
                    b.Navigation("evacuationPlans");
                });

            modelBuilder.Entity("evacuation.Domain.Entities.EvacuationZone", b =>
                {
                    b.Navigation("evacuationPlans");
                });

            modelBuilder.Entity("evacuation.Domain.Entities.VehicleTypes", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("evacuation.Domain.Entities.Vehicles", b =>
                {
                    b.Navigation("evacuationPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
